name: Build Chrome extension

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        shell: bash

      - name: Build extension
        run: npm run build --if-present
        shell: bash

      - name: Pack extension
        run: zip -r extension-${{ github.event.pull_request.head.sha }}.zip *
        working-directory: dist
        shell: bash

      - name: Upload extension archive
        uses: actions/upload-artifact@v3
        with:
          name: extension-${{ github.sha }}
          path: dist/extension-${{ github.event.pull_request.head.sha }}.zip
