name: Build Chrome extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Update to v4 for best compatibility

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Update to v4
        with:
          node-version: 18

      - name: Pack extension
        working-directory: .
        run: |
          mkdir -p out  # Ensure the 'out' directory exists
          zip -r out/extension-${{ github.sha }}.zip *

      - name: Upload extension archive
        uses: actions/upload-artifact@v4  # Upgrade from v3 to v4
        with:
          name: extension-${{ github.sha }}
          path: out/extension-${{ github.sha }}.zip
